### ISSUE TITLE
Create responsive website layout

### ISSUE THREAD

**Issue by AlexeyKopchinskiy** [AlexeyKopchinskiy/Portfolio-project-1#1]
- [ ] The website should be responsive across multiple platforms and screen sizes
- [ ] The website should have clearly visible and intuitive navigation
- [ ] Website images should be engaging 

**Tasks**

- [ ] Create responsive website layout using Bootstrap 5
- [ ] Use Bootstrap principles for creating responsive navbar
- [ ] Use AI tools for creating engaging images
- [ ] Position images within the bootstrap template so that they are catchy but responsive
