### ISSUE TITLE
Add site descriptios

### ISSUE THREAD

**Issue by AlexeyKopchinskiy** [AlexeyKopchinskiy/Portfolio-project-1#2]
**The goal**

Website should have valid text description optimized for search engines such as Google and Bing

**Acceptance criteria**

- [ ] Update website HEAD with correct textual data

**Tasks**

- [ ] Add text to Title
- [ ] Add text to Description
- [ ] Add text to kaywords
