### ISSUE TITLE
Website Images

### ISSUE THREAD

**Issue by AlexeyKopchinskiy** [AlexeyKopchinskiy/Portfolio-project-1#3]
**Goal**

Make the website attractive image-wise

- [ ] Website images should be engaging and professionally looking
- [ ] Images should be responsive and adopt to any device and screen size
- [ ] Images should have clear desriptions

**Tasks**

- [ ] Use AI tools for creating engaging images
- [ ] Enhance images in Photoshop if necessary
- [ ] Position images within the bootstrap template so that they are catchy but responsive
- [ ] And image descriptions to alt and title tags
