### ISSUE TITLE
Site gallery

### ISSUE THREAD

**Issue by AlexeyKopchinskiy** [AlexeyKopchinskiy/Portfolio-project-1#5]
Goal

There should be a small image gallery on the landing page that would familiarize potential customer with the attractions included in the guided tours

**Acceptance criteria**

- [ ] There should be at least 6 images in the gallery depicting the main tour destinations
- [ ] Each image should have clear text description and cab be enlarged

**Tasks**

- [ ] Use AI image generator in order to produce professionally-looking photos of the imperial palace and surrounding park
- [ ] Use Bootstrap for positioning of the images in two rows with with three columns in each row
- [ ] And a link to the larger image so that it opens in the new window
