### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by AlexeyKopchinskiy** [AlexeyKopchinskiy/Portfolio-project-1#6]
**Goal** 

The website should have "Contact us" section with all contact information available in a clear and responsive way

**Acceptance criteria**

- [ ] The contact information should readily available after clicking corresponding menu link
- [ ] The text in the Contact us section should be contrast and have all necessary information

**Tasks**

- [ ] Connect the "Contact" link in the menu bar with "Contact us" section on the landing page
- [ ] Make the contact text clearly visible using light-colored font on the dark background
