### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by AlexeyKopchinskiy** [AlexeyKopchinskiy/Portfolio-project-1#7]
**Goal**

The about us section should clearly explain to the customers who is behind the offered services so that they rest assured the information is valid and the company is trustworthy

**Acceptance criteria**

- [ ] Section "About us" should have short but clear and attractive text informing the potential customer about the company details

**Tasks**

- [ ] Cerate section "About us"
- [ ] Add high quality description of the company 
- [ ] Use AI tools to generate best possible text for the company description
